
# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [2]:
import numpy as np
a = np.random.random((3,5))
b = np.random.random((3,5))
print (a, "\n", b)

[[0.22320962 0.9763014  0.20288127 0.62332067 0.84071878]
 [0.52873814 0.45673583 0.69533847 0.41962544 0.94242399]
 [0.03807619 0.29910931 0.6137381  0.76391685 0.67884613]] 
 [[0.53127055 0.86415549 0.41502916 0.44325933 0.56880099]
 [0.8796828  0.51964823 0.64163537 0.79743028 0.39519008]
 [0.8343689  0.61799083 0.0708893  0.93801279 0.46280068]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [0]:

c = np.arange(0,100)
d = np.zeros((3,3))
# print (c , d)

We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [4]:
e = [[1,2,3],[4,5,6],[7,8,9]]

e = np.array(e)
print (e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [5]:
f = np.ones( (5,5), dtype=int )
g = np.eye(5)
print(f)
print (g)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [6]:
h = c.reshape(10,10)
if h == h.ravel():
  print ("YES")
else:
  print ("NO")

NO


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


 Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [7]:
A = np.random.rand(2,10,5)
print(np.transpose(A,(2, 0, 1)))


[[[4.72874572e-02 3.00107381e-01 8.44869853e-01 9.56912008e-01
   3.38110209e-02 7.82494930e-01 1.96471945e-01 3.79983128e-01
   2.28466696e-01 9.88174950e-01]
  [6.09281169e-01 8.08129061e-01 2.93142877e-01 7.31151337e-01
   3.87607390e-01 4.40951157e-01 5.48646693e-02 1.70096769e-01
   3.43503323e-01 8.28836351e-01]]

 [[8.80720097e-01 7.26069168e-01 8.99292877e-01 9.20316288e-01
   4.73068267e-01 3.63351416e-03 3.68163005e-01 3.06521370e-01
   5.75331858e-02 8.51099836e-01]
  [1.00644570e-01 4.49841938e-01 4.59141118e-01 1.87777371e-01
   5.16962269e-01 5.01659856e-01 7.24905205e-01 5.09521955e-01
   8.42261316e-02 5.06175245e-01]]

 [[5.25636043e-01 9.20223077e-01 9.35059965e-04 8.12663153e-01
   4.83638085e-01 2.84612410e-01 7.93052434e-01 6.74336070e-01
   5.99151191e-01 2.02510534e-01]
  [2.65648019e-01 6.23207799e-01 4.16762900e-01 9.14949369e-01
   2.38378830e-01 4.72111596e-01 4.21847528e-01 3.12992537e-02
   9.10771759e-01 7.86867568e-01]]

 [[9.50964843e-01 2.85262332e-01 8

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [27]:
np.random.seed(0)
X = np.random.rand(10,5)
# print("Minimum value and index where it occured, for each column =", X)
# ind1 =  X.argmin(axis=0)
# print (ind1)
print(X)
print("Minimum value, for each column =",X.min(axis=0), "index where it occured", X.argmin(axis=0))
print("Maximum value and index where it occured, for each column =",X.max(axis=0), "index where it occured", X.argmax(axis=0))
print("Minimum value and index where it occured, for each row =",X.min(axis=1), "index where it occured", X.argmin(axis=1))
print("Maximum value and index where it occured, for each row =",X.max(axis=1), "index where it occured", X.argmax(axis=1) )
print("Minimum value and index where it occured, for the entire matrix =",X.min(), "index where it occured", X.argmin())
print("Maximum value and index where it occured, for the entire matrix =",X.max(), "index where it occured", X.argmax() )


[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]
Minimum value, for each column = [0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ] index where it occured [3 3 9 8 6]
Maximum value and index where it occured, for each column = [0.97861834 0.79915856 0.94466892 0.96366276 0.87001215] index where it occured [4 4 5 1 3]
Minimum value and index where it occured, for each row = [0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.6120

Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [38]:
mean_row = np.mean(X, axis=1)
mean_col = np.mean(X, axis=0)
std_X = np.std(X)
std_X_col = np.std(X, axis=0)
std_X_row = np.std(X, axis=1)
# print(X)
print("STD matrix =",std_X)
print("STD col =",std_X_col)
print("STD row =",std_X_row)
print ("mean_row = ",mean_row)
print ("mean_col = " ,mean_col)

STD matrix = 0.27226582292177587
STD col = [0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]
STD row = [0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332]
mean_row =  [0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717]
mean_col =  [0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [60]:
np.random.seed(3)
Y = np.random.rand(10,10)
# Y = np.zeros((3,3))
print(Y)
print("Determinant =",np.linalg.det(Y))
print("Rank =",np.linalg.matrix_rank(Y))
print("Diagonal =",np.diagonal(Y))
print("Trace =",np.trace(Y))
print("Eigen Values =",np.linalg.eig(Y))
u, s, vh = np.linalg.svd(a, full_matrices=True)
print (u, s, vh)
inv_or_psudoinv = np.zeros((10,10))
try: 
  inv_or_psudoinv = np.linalg.inv(Y)
  print("Inverse =", np.linalg.inv(Y))
except:
  inv_or_psudoinv = np.linalg.pinv(Y)
  print("Inverse does not exist the psudo inverse is =", np.linalg.pinv(Y))
print("multiplication of Y and X is = ", np.matmul(Y, X), np.matmul(Y, X).shape)
print("Element wise multiplication Y and inverse / psudo inverse", inv_or_psudoinv * Y, np.matmul(Y, inv_or_psudoinv))

[[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695 0.89629309
  0.12558531 0.20724288 0.0514672  0.44080984]
 [0.02987621 0.45683322 0.64914405 0.27848728 0.6762549  0.59086282
  0.02398188 0.55885409 0.25925245 0.4151012 ]
 [0.28352508 0.69313792 0.44045372 0.15686774 0.54464902 0.78031476
  0.30636353 0.22195788 0.38797126 0.93638365]
 [0.97599542 0.67238368 0.90283411 0.84575087 0.37799404 0.09221701
  0.6534109  0.55784076 0.36156476 0.2250545 ]
 [0.40651992 0.46894025 0.26923558 0.29179277 0.4576864  0.86053391
  0.5862529  0.28348786 0.27797751 0.45462208]
 [0.20541034 0.20137871 0.51403506 0.08722937 0.48358553 0.36217621
  0.70768662 0.74674622 0.69109292 0.68918041]
 [0.37360012 0.6681348  0.33984866 0.57279387 0.32580716 0.44514505
  0.06152893 0.24267542 0.97160261 0.2305842 ]
 [0.69147751 0.65047686 0.72393914 0.47508861 0.59666377 0.06696942
  0.07256214 0.19897603 0.151861   0.10010434]
 [0.12929386 0.55327773 0.18781482 0.95210124 0.68161178 0.54101967
  0.7071806 

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"
r = requests.get(file_url, stream = True) 


### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.